### ISSUE TITLE
The tool give me a screenshot of black on linux

### ISSUE THREAD

**Issue by XCE0** [raikasdev/mastopoet#36] opened 2023-09-04 17:53 UTC
when I try to use the tool on chromuim browser running clearlinux on wayland the tool outputs a black image .

![mastopoet-raikas-28072023](https://github.com/raikasdev/mastopoet/assets/143923725/7507c989-1b84-41b0-a283-d7f2a6c021d7)

**Comment by raikasdev** [comment] 2023-09-05 12:39
Does this occur on other browsers? I might not be able to fix this, because it's probably caused by your operating systems modifications or browser extensions.

**Comment by XCE0** [comment] 2023-09-05 12:58
no, I think the problem might be the way the tool saves the photo file.

So I could see in the preview the toot but when I download it outputs black photo.


the session runs in wayland the browser window is running in x.org,

**Comment by raikasdev** [comment] 2023-09-05 12:59
The preview is raw HTML. The image is created using HTML canvas. Please test with other browsers, or I will close this issue. Thank you!

**Comment by XCE0** [comment] 2023-09-05 14:10
that is what I was saying, no it does not happen with the other browsers, so I think the issue is with the way the image is created and I feel that finding other way to save the image will be better.

**Comment by raikasdev** [comment] 2023-09-05 14:28
I have not received any reports of this on other OSes running Chromium. Are you 100% sure you don't have any "security" and "anti-fingerprinting" extensions or settings enabled. If you are able to find the root cause, I'll glady reopen this for fixing, but for now I'm closing this.

**Closed by raikasdev** 2023-09-05 14:28 UTC
